
package org.example.serviceproxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProductsService", targetNamespace = "http://www.example.org/products", wsdlLocation = "http://localhost:8080/ws/products.wsdl")
public class ProductsService
    extends Service
{

    private final static URL PRODUCTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSSERVICE_EXCEPTION;
    private final static QName PRODUCTSSERVICE_QNAME = new QName("http://www.example.org/products", "ProductsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/products.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSSERVICE_WSDL_LOCATION = url;
        PRODUCTSSERVICE_EXCEPTION = e;
    }

    public ProductsService() {
        super(__getWsdlLocation(), PRODUCTSSERVICE_QNAME);
    }

    public ProductsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSSERVICE_QNAME, features);
    }

    public ProductsService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSSERVICE_QNAME);
    }

    public ProductsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSSERVICE_QNAME, features);
    }

    public ProductsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductsPort
     */
    @WebEndpoint(name = "ProductsPortSoap11")
    public ProductsPort getProductsPortSoap11() {
        return super.getPort(new QName("http://www.example.org/products", "ProductsPortSoap11"), ProductsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductsPort
     */
    @WebEndpoint(name = "ProductsPortSoap11")
    public ProductsPort getProductsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/products", "ProductsPortSoap11"), ProductsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSSERVICE_EXCEPTION!= null) {
            throw PRODUCTSSERVICE_EXCEPTION;
        }
        return PRODUCTSSERVICE_WSDL_LOCATION;
    }

}
