
package org.example.serviceproxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductsPort", targetNamespace = "http://www.example.org/products")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductsPort {


    /**
     * 
     * @param createProductRequest
     * @return
     *     returns org.example.serviceproxy.CreateProductResponse
     */
    @WebMethod
    @WebResult(name = "createProductResponse", targetNamespace = "http://www.example.org/products", partName = "createProductResponse")
    public CreateProductResponse createProduct(
        @WebParam(name = "createProductRequest", targetNamespace = "http://www.example.org/products", partName = "createProductRequest")
        CreateProductRequest createProductRequest);

    /**
     * 
     * @param deleteProductRequest
     * @return
     *     returns org.example.serviceproxy.DeleteProductResponse
     */
    @WebMethod
    @WebResult(name = "deleteProductResponse", targetNamespace = "http://www.example.org/products", partName = "deleteProductResponse")
    public DeleteProductResponse deleteProduct(
        @WebParam(name = "deleteProductRequest", targetNamespace = "http://www.example.org/products", partName = "deleteProductRequest")
        DeleteProductRequest deleteProductRequest);

    /**
     * 
     * @param getProductRequest
     * @return
     *     returns org.example.serviceproxy.GetProductResponse
     */
    @WebMethod
    @WebResult(name = "getProductResponse", targetNamespace = "http://www.example.org/products", partName = "getProductResponse")
    public GetProductResponse getProduct(
        @WebParam(name = "getProductRequest", targetNamespace = "http://www.example.org/products", partName = "getProductRequest")
        GetProductRequest getProductRequest);

    /**
     * 
     * @param getAllProductsRequest
     * @return
     *     returns org.example.serviceproxy.GetAllProductsResponse
     */
    @WebMethod
    @WebResult(name = "getAllProductsResponse", targetNamespace = "http://www.example.org/products", partName = "getAllProductsResponse")
    public GetAllProductsResponse getAllProducts(
        @WebParam(name = "getAllProductsRequest", targetNamespace = "http://www.example.org/products", partName = "getAllProductsRequest")
        GetAllProductsRequest getAllProductsRequest);

    /**
     * 
     * @param updateProductRequest
     * @return
     *     returns org.example.serviceproxy.UpdateProductResponse
     */
    @WebMethod
    @WebResult(name = "updateProductResponse", targetNamespace = "http://www.example.org/products", partName = "updateProductResponse")
    public UpdateProductResponse updateProduct(
        @WebParam(name = "updateProductRequest", targetNamespace = "http://www.example.org/products", partName = "updateProductRequest")
        UpdateProductRequest updateProductRequest);

}
