package org.example.serviceproxy;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-25T19:31:27.707+03:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "ProductService",
                  wsdlLocation = "http://localhost:8080/services/ProductService?wsdl",
                  targetNamespace = "http://service.example.org/")
public class ProductService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://service.example.org/", "ProductService");
    public static final QName ProductServiceImplPort = new QName("http://service.example.org/", "ProductServiceImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/services/ProductService?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/ProductService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProductService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductService getProductServiceImplPort() {
        return super.getPort(ProductServiceImplPort, ProductService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceImplPort")
    public ProductService getProductServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ProductServiceImplPort, ProductService.class, features);
    }

}
