
package org.example.serviceproxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CountriesService", targetNamespace = "http://www.example.org/", wsdlLocation = "http://localhost:8080/ws/countries.wsdl")
public class CountriesService
    extends Service
{

    private final static URL COUNTRIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRIESSERVICE_EXCEPTION;
    private final static QName COUNTRIESSERVICE_QNAME = new QName("http://www.example.org/", "CountriesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/countries.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRIESSERVICE_WSDL_LOCATION = url;
        COUNTRIESSERVICE_EXCEPTION = e;
    }

    public CountriesService() {
        super(__getWsdlLocation(), COUNTRIESSERVICE_QNAME);
    }

    public CountriesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRIESSERVICE_QNAME, features);
    }

    public CountriesService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRIESSERVICE_QNAME);
    }

    public CountriesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRIESSERVICE_QNAME, features);
    }

    public CountriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountriesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountriesPort
     */
    @WebEndpoint(name = "CountriesPortSoap11")
    public CountriesPort getCountriesPortSoap11() {
        return super.getPort(new QName("http://www.example.org/", "CountriesPortSoap11"), CountriesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountriesPort
     */
    @WebEndpoint(name = "CountriesPortSoap11")
    public CountriesPort getCountriesPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/", "CountriesPortSoap11"), CountriesPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRIESSERVICE_EXCEPTION!= null) {
            throw COUNTRIESSERVICE_EXCEPTION;
        }
        return COUNTRIESSERVICE_WSDL_LOCATION;
    }

}
